from __future__ import annotations

from typing import Protocol


class OrganizationRepositoryPort(Protocol):
    async def get_actor_state(self, user_id: int): ...
    async def get_scope_chain(self, user_id: int): ...
    async def list_tree(self, **kwargs): ...
    async def get_detail(self, organization_id: int): ...
    async def list_tenants(self, **kwargs): ...
    async def list_admin_candidates(self, **kwargs): ...
    async def create(self, **kwargs): ...
    async def patch(self, **kwargs): ...
    async def reorder(self, **kwargs): ...
    async def change_status(self, **kwargs): ...


class OrganizationUnitOfWorkPort(Protocol):
    repository: OrganizationRepositoryPort

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
