from __future__ import annotations

from typing import Mapping, Protocol
from uuid import UUID


class HealthPlanRepositoryPort(Protocol):
    async def generation_authority(
        self, service_case_id: UUID, actor_user_id: int, actor_role: str
    ) -> dict | None: ...

    async def generation_replay(
        self, actor_user_id: int, idempotency_key: str, request_digest: str
    ) -> dict | None: ...

    async def create_generation_request(self, payload: Mapping[str, object]) -> dict: ...

    async def claim_generation(self, request_id: UUID, lease_owner: str) -> dict | None: ...

    async def generation_input(self, request_id: UUID) -> dict | None: ...

    async def complete_generation(self, payload: Mapping[str, object]) -> dict: ...

    async def fail_generation(self, payload: Mapping[str, object]) -> dict: ...

    async def transition_review(self, operation: str, payload: Mapping[str, object]) -> dict: ...

    async def explain_plan(self, payload: Mapping[str, object]) -> dict: ...

    async def decide_plan(self, payload: Mapping[str, object]) -> dict: ...
