from typing import Protocol, Sequence

from .domain import HealthIndicatorLegacyMapping, HealthIndicatorSourceSnapshot


class HealthFactMappingRepositoryPort(Protocol):
    async def find_existing(self, legacy_indicator_id: int, legacy_recorded_at, mapping_version: int): ...
    async def add(self, mapping): ...
    async def add_audit(self, mapping, action: str): ...
    async def has_audit(self, mapping_id: int, action: str) -> bool: ...
    async def list_shadow_sources(self, high_watermark) -> Sequence[HealthIndicatorSourceSnapshot]: ...
    async def list_shadow_mappings(self, high_watermark, mapping_version: int) -> Sequence[HealthIndicatorLegacyMapping]: ...
    async def get_shadow_canonical(self, fact_id: int): ...


class HealthFactMappingUnitOfWorkPort(Protocol):
    fact_repository: object
    mapping_repository: HealthFactMappingRepositoryPort
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc, traceback): ...
    async def commit(self): ...
    async def rollback(self): ...
