from __future__ import annotations

from typing import Protocol, Sequence

from .domain import OrganizationLegacyMapping, OrganizationSourceSnapshot


class OrganizationMappingRepositoryPort(Protocol):
    async def get_source(self, legacy_tenant_id: int) -> OrganizationSourceSnapshot: ...
    async def find_existing(self, legacy_tenant_id: int, mapping_version: int): ...
    async def add(self, mapping: OrganizationLegacyMapping): ...
    async def add_audit(self, mapping: OrganizationLegacyMapping, action: str): ...
    async def has_audit(self, mapping_id: int, action: str) -> bool: ...
    async def list_shadow_sources(self, high_watermark) -> Sequence[OrganizationSourceSnapshot]: ...
    async def list_shadow_mappings(self, high_watermark, mapping_version: int) -> Sequence[OrganizationLegacyMapping]: ...
    async def get_shadow_canonical(self, organization_id: int): ...


class OrganizationMappingUnitOfWorkPort(Protocol):
    repository: OrganizationMappingRepositoryPort
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc, traceback): ...
    async def commit(self): ...
    async def rollback(self): ...


class OrganizationMappingReaderPort(Protocol):
    async def list_unprocessed(self, *, mapping_version: int, high_watermark: int, limit: int) -> Sequence[int]: ...
