from typing import Protocol, Sequence

from .domain import HealthCurrentFact, HealthProjectionFactRow, HealthWindowSelection


class HealthProjectionCorePort(Protocol):
    def project(
        self, *, facts: Sequence[HealthCurrentFact], digest_key: bytes
    ) -> tuple[list[HealthProjectionFactRow], list[HealthWindowSelection]]: ...

class HealthProjectionBuilderRepositoryPort(Protocol):
    async def max_source_id(self) -> int: ...
    async def list_source_ids(self, *, after_id: int | None, max_id: int, limit: int) -> tuple[int, ...]: ...
    async def load_facts(self, ids: tuple[int, ...]) -> tuple[HealthCurrentFact, ...]: ...
    async def get_generation(self, generation_id: int, *, lock: bool = False): ...
    async def get_checkpoint(self, generation_id: int, *, lock: bool = False): ...
