from __future__ import annotations

from typing import Protocol


class DirectOnboardingRepositoryPort(Protocol):
    async def create(self, envelope: dict) -> dict: ...
    async def activate(self, envelope: dict) -> dict: ...
    async def submit_compliance(self, envelope: dict) -> dict: ...
    async def decide_compliance(self, envelope: dict) -> dict: ...
    async def replay(self, operation: str, scope: str, key: str, digest: str): ...

