from typing import Protocol, Sequence

from .domain import OrganizationProjectionRow, OrganizationSourceNode


class OrganizationProjectionCorePort(Protocol):
    def project(
        self, *, chain: Sequence[OrganizationSourceNode], digest_key: bytes
    ) -> OrganizationProjectionRow: ...

class OrganizationProjectionBuilderRepositoryPort(Protocol):
    async def max_source_id(self) -> int: ...
    async def list_leaf_ids(self, *, after_id: int | None, max_id: int, limit: int) -> tuple[int, ...]: ...
    async def load_chain(self, leaf_id: int) -> tuple[OrganizationSourceNode, ...]: ...
    async def get_generation(self, generation_id: int, *, lock: bool = False): ...
    async def get_checkpoint(self, generation_id: int, *, lock: bool = False): ...


class OrganizationProjectionShadowRepositoryPort(Protocol):
    async def get_shadow_generation(self, generation_id: int, *, lock: bool = False): ...
    async def load_shadow_inputs(self, generation): ...
    async def get_shadow_run(self, run_id: str, *, lock: bool = False): ...
    async def get_shadow_audit(self, operation_id: str): ...
    async def next_shadow_sequence(self, generation_id: int) -> int: ...
    async def passed_shadow_runs(self, generation_id: int): ...
