from __future__ import annotations

from datetime import date, datetime
from typing import Protocol
from uuid import UUID


class ClockPort(Protocol):
    def now(self) -> datetime: ...


class UuidPort(Protocol):
    def generate(self) -> UUID: ...


class MemberEnrollmentSecretsPort(Protocol):
    def encrypt(self, *, field: str, tenant_public_id: UUID, object_id: UUID, plaintext: str) -> tuple[bytes, str]: ...
    def decrypt(self, *, field: str, tenant_public_id: UUID, object_id: UUID, ciphertext: bytes, key_id: str) -> str: ...
    def digest_candidates(self, *, domain: str, value: str) -> tuple[tuple[str, str], ...]: ...
    def current_digest(self, *, domain: str, value: str) -> tuple[str, str]: ...
    def short_code(self) -> str: ...
    def digest_payload(self, value: object) -> str: ...


class VerifiedAdultEligibilityPort(Protocol):
    async def verified_birth_date_for_update(self, *, user_id: int, member_id: UUID) -> tuple[date, UUID, UUID, int, str]: ...


class ActorCurrentnessPort(Protocol):
    async def require_institution_actor(self, *, user_id: int, tenant_id: int) -> None: ...
    async def require_family_actor(self, *, user_id: int) -> UUID: ...
    async def require_platform_reviewer(self, *, user_id: int) -> None: ...
    async def require_therapist(self, *, user_id: int) -> tuple[UUID, int]: ...


class ReadinessGuardPort(Protocol):
    async def require_service_ready(self, *, tenant_id: int) -> tuple[int, str]: ...


class PasswordStepUpPort(Protocol):
    async def verify(self, *, user_id: int, password: str) -> str: ...


class WorkflowPublisherPort(Protocol):
    async def publish(self, *, event_id: UUID) -> None: ...


class MemberEnrollmentRepositoryPort(Protocol):
    async def lock_operation(self, actor_scope: str, operation: str, target_id: UUID, key: str) -> None: ...
    async def lock_identity_review_boundary(self, verification_id: UUID) -> None: ...
    async def invitation_for_update(self, invitation_id: UUID): ...
    async def enrollment_for_update(self, enrollment_id: UUID): ...
    async def verification_for_update(self, verification_id: UUID): ...
    async def assignment_for_update(self, assignment_id: UUID): ...
    async def proxy_grant_for_update(self, grant_id: UUID): ...
    async def consent_for_update(self, consent_record_id: UUID): ...
