from __future__ import annotations

from typing import Mapping, Protocol
from uuid import UUID


class HealthAssessmentRepositoryPort(Protocol):
    async def start_authority(self, service_case_id: UUID, actor_user_id: int) -> dict | None: ...

    async def write_assessment_start(self, payload: Mapping[str, object]) -> dict: ...

    async def claim_assessment(self, assessment_id: UUID, lease_owner: str) -> dict | None: ...

    async def complete_assessment(self, payload: Mapping[str, object]) -> dict: ...

    async def transition_high_risk_task(self, payload: Mapping[str, object]) -> dict: ...

    async def assessment_detail(self, assessment_id: UUID) -> dict | None: ...

    async def assessment_page(self, scope: Mapping[str, object]) -> list[dict]: ...

    async def task_detail(self, task_id: UUID) -> dict | None: ...

    async def task_page(self, scope: Mapping[str, object]) -> list[dict]: ...
